# Generated by Django 2.0.1 on 2022-06-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=150, null=True, verbose_name='Start Point')),
                ('end_point', models.CharField(max_length=150, null=True, verbose_name='End Point')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Distance')),
                ('emission', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Emission')),
                ('order', models.IntegerField(null=True, verbose_name='Order')),
                ('lat_start_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Lat start point')),
                ('long_start_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Long start point')),
                ('lat_end_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Lat end point')),
                ('long_end_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Long end point')),
                ('vehicle_type', models.CharField(blank=True, choices=[('MRT', 'MRT'), ('Train', 'Train'), ('Bus', 'Bus'), ('Car', 'Car'), ('GrabCar', 'GrabCar'), ('GrabBike', 'GrabBike')], max_length=32, null=True, verbose_name='Vehicle Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Journey Detail',
                'verbose_name_plural': 'Journey Details',
                'db_table': 'journey_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('start_point', models.CharField(max_length=150, null=True, verbose_name='Start Point')),
                ('end_point', models.CharField(max_length=150, null=True, verbose_name='End Point')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Distance')),
                ('miles', models.IntegerField(null=True, verbose_name='Miles')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('type', models.CharField(blank=True, choices=[('MRT', 'MRT'), ('Train', 'Train'), ('Bus', 'Bus')], max_length=32, null=True, verbose_name='Journey Type')),
                ('emission_occured', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Emission Occured')),
                ('emission_actual', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Emission Actual')),
                ('emission_reduced', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Emission Reduced')),
                ('journey_map', models.TextField(null=True, verbose_name='Journey Map')),
                ('lat_start_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Lat start point')),
                ('long_start_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Long start point')),
                ('lat_end_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Lat end point')),
                ('long_end_point', models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='Long end point')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
                'db_table': 'journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('level', models.CharField(max_length=150, null=True, verbose_name='Level')),
                ('miles', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Miles')),
                ('journeys', models.IntegerField(null=True, verbose_name='Quantity')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Profiles',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('claimed', 'claimed'), ('unclaimed', 'unclaimed')], max_length=32, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_profile_id', to='rest_admin.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'db_table': 'rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('expired', 'expired')], max_length=32, null=True, verbose_name='Discount Type')),
                ('expired_at', models.DateTimeField(null=True, verbose_name='Expired At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_profile_id', to='rest_admin.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'User Voucher',
                'verbose_name_plural': 'User Vouchers',
                'db_table': 'user_vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(max_length=150, null=True, verbose_name='Type')),
                ('terms', models.TextField(null=True, verbose_name='Terms')),
                ('thumbnail', models.TextField(null=True, verbose_name='Thumbnail')),
                ('title', models.TextField(null=True, verbose_name='Title')),
                ('amount', models.IntegerField(null=True, verbose_name='Amount')),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'percentage'), ('fixed', 'fixed')], max_length=32, null=True, verbose_name='Discount Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uservouchers',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_id', to='rest_admin.Vouchers', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_voucher_id', to='rest_admin.Vouchers', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='journeys',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to='rest_admin.Profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey_id', to='rest_admin.Journeys', verbose_name='Journey'),
        ),
    ]
