# Generated by Django 2.0.1 on 2022-06-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0002_profile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='Thumbnail')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('target', models.IntegerField(blank=True, null=True, verbose_name='Target')),
                ('challenge_type', models.CharField(blank=True, choices=[('first', 'first'), ('journey', 'journey'), ('distance', 'distance'), ('miles', 'miles'), ('daily', 'daily')], max_length=32, null=True, verbose_name='Status')),
                ('due_date', models.DateTimeField(auto_now_add=True, verbose_name='Due Date')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('expired', 'expired')], max_length=32, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_id', to='rest_admin.Challenge', verbose_name='Challenge'),
        ),
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_profile_id', to='rest_admin.Profile', verbose_name='Profile'),
        ),
    ]
