# Generated by Django 2.0.1 on 2022-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0003_auto_20220612_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='miles',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Distance'),
        ),
    ]
