# Generated by Django 2.0.1 on 2022-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0004_auto_20220612_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journeys',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservouchers',
            name='user',
        ),
        migrations.AddField(
            model_name='badge',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='journeys',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='uservouchers',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='User'),
        ),
    ]
