# Generated by Django 2.0.1 on 2022-06-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0005_auto_20220612_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='challenge',
            name='thumbnail_active',
            field=models.TextField(blank=True, null=True, verbose_name='Thumbnail Active'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='thumbnail_inactive',
            field=models.TextField(blank=True, null=True, verbose_name='Thumbnail Inactive'),
        ),
    ]
