# Generated by Django 2.0.1 on 2022-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0006_auto_20220612_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='thumbnail_active',
            field=models.TextField(null=True, verbose_name='Thumbnail Active'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='thumbnail_inactive',
            field=models.TextField(null=True, verbose_name='Thumbnail Inactive'),
        ),
    ]
